import { Issue } from '@/types'

export const MOCK_ISSUES: Issue[] = [
  {
    id: '1',
    title: '반도체 산업 국가지원 특별법',
    summary: '반도체 기업에 세액공제 최대 25% 확대 및 국가 보조금 지원을 위한 특별법 제정 논의',
    description: '글로벌 반도체 패권 경쟁에서 대한민국의 경쟁력 유지를 위해 삼성·SK하이닉스 등 국내 반도체 기업에 대규모 국가 지원이 필요하다는 주장과, 대기업 특혜·재정 부담 우려가 맞서고 있습니다.',
    category: '경제',
    party: '국민의힘',
    proposer: '양향자',
    bill_no: '2201234',
    assembly_session: 22,
    status: 'active',
    source_url: null,
    pro_summary: '미국·중국·EU가 자국 반도체 산업에 막대한 보조금을 지원하는 상황에서 국가 지원 없이는 글로벌 경쟁에서 뒤처질 수 있습니다. 고용 창출과 기술 자립 효과도 큽니다.',
    con_summary: '대기업 위주의 특혜성 지원으로 중소기업과의 형평성 문제가 있으며, 천문학적 재정 지출이 국민 세부담으로 돌아올 수 있습니다.',
    api_data: { bill_stage_idx: 1, bill_stage_date: '20260421', PROPOSE_DT: '20260321' },
    agree_count: 12847,
    disagree_count: 8934,
    comment_count: 342,
    featured: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: '최저임금 1만 2,000원 인상안',
    summary: '2026년 최저임금을 현재 대비 약 5.4% 인상한 1만 2,000원으로 결정하는 안',
    description: '노동계는 물가 상승과 생계비 증가를 반영해 더 높은 인상을 요구하는 반면, 경영계는 소상공인과 중소기업의 경영 부담 가중을 이유로 반대하고 있습니다.',
    category: '경제',
    party: '더불어민주당',
    proposer: '이수진',
    bill_no: null,
    assembly_session: null,
    status: 'active',
    source_url: null,
    pro_summary: '물가 상승으로 실질 임금이 떨어진 저임금 노동자의 생계를 보호하고, 내수 소비 진작 효과를 기대할 수 있습니다.',
    con_summary: '인건비 부담이 커지면 소상공인·자영업자가 폐업하거나 고용을 줄일 수 있으며, 결국 취약계층에게 역효과가 날 수 있습니다.',
    api_data: { bill_stage_idx: 2, bill_stage_date: '20260510', PROPOSE_DT: '20260401' },
    agree_count: 21453,
    disagree_count: 19876,
    comment_count: 892,
    featured: true,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: '군 복무기간 단축 (18개월 → 16개월)',
    summary: '현행 육군 기준 18개월 복무기간을 16개월로 단축하는 병역법 개정안',
    description: '청년들의 경력 단절을 최소화하고 저출생 대응 차원에서 복무기간 단축이 필요하다는 주장과, 안보 공백 및 전력 약화 우려가 대립하고 있습니다.',
    category: '안보',
    party: '더불어민주당',
    proposer: '김병주',
    bill_no: null,
    assembly_session: null,
    status: 'active',
    source_url: null,
    pro_summary: '청년의 사회 진출 시기를 앞당기고 인구 감소 시대에 경제활동 인구를 늘릴 수 있습니다. 스마트 국방 전환으로 충분히 전력을 유지할 수 있습니다.',
    con_summary: '북한 핵·미사일 위협이 고조되는 상황에서 복무기간 단축은 군 전투력 약화로 이어질 수 있으며, 충분한 훈련 시간을 확보하기 어렵습니다.',
    api_data: { bill_stage_idx: 0, bill_stage_date: '20260501', PROPOSE_DT: '20260501' },
    agree_count: 34521,
    disagree_count: 28765,
    comment_count: 1204,
    featured: false,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: '저출생 대응 출산장려금 월 100만원 지급',
    summary: '신생아 출생 후 1년간 월 100만원 출산지원금 지급 및 육아휴직급여 확대 정책',
    description: '세계 최저 수준의 합계출산율(0.72명) 위기를 극복하기 위한 현금 지원 확대 정책입니다.',
    category: '복지',
    party: '국민의힘',
    proposer: '정부',
    bill_no: null,
    assembly_session: null,
    status: 'active',
    source_url: null,
    pro_summary: '출산·양육의 경제적 부담을 직접 줄여주는 실질적인 지원이며, 육아 기간 소득 안정으로 출산 기피 현상을 완화할 수 있습니다.',
    con_summary: '현금 지원만으로는 구조적 저출생 문제 해결이 어렵습니다. 연간 수십조 원의 재정 부담이 발생합니다.',
    api_data: { bill_stage_idx: 3, bill_stage_date: '20260515', PROPOSE_DT: '20260310' },
    agree_count: 45231,
    disagree_count: 12043,
    comment_count: 2341,
    featured: false,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: '의대 정원 확대 (2,000명 증원)',
    summary: '의과대학 입학 정원을 현재 3,058명에서 5,058명으로 확대하는 정책',
    description: '의사 수 부족으로 인한 지역·필수의료 붕괴를 해결하기 위한 정원 확대 정책과 의사 집단의 반발이 첨예하게 대립하고 있습니다.',
    category: '의료',
    party: '정부',
    proposer: '정부',
    bill_no: null,
    assembly_session: null,
    status: 'active',
    source_url: null,
    pro_summary: 'OECD 평균 대비 의사 수가 부족하며, 특히 농어촌 지역과 응급·소아과 등 필수의료 분야의 의사 부족이 심각합니다.',
    con_summary: '단순 증원보다 의사의 지역 배치와 처우 개선이 선행되어야 합니다. 갑작스러운 대규모 증원은 의학교육 질 저하를 초래할 수 있습니다.',
    api_data: { bill_stage_idx: 4, bill_stage_date: '20260519', PROPOSE_DT: '20260201' },
    agree_count: 67432,
    disagree_count: 54321,
    comment_count: 4521,
    featured: true,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_VOTES_BY_ISSUE: Record<string, {
  byAge: Array<{ label: string; agree: number; disagree: number; total: number }>
  byGender: Array<{ label: string; agree: number; disagree: number; total: number }>
}> = {
  '5': {
    byAge: [
      { label: '20대', agree: 8200, disagree: 7100, total: 15300 },
      { label: '30대', agree: 14300, disagree: 11200, total: 25500 },
      { label: '40대', agree: 19800, disagree: 16400, total: 36200 },
      { label: '50대', agree: 12100, disagree: 11900, total: 24000 },
      { label: '60대이상', agree: 7300, disagree: 6200, total: 13500 },
    ],
    byGender: [
      { label: '남성', agree: 31200, disagree: 28900, total: 60100 },
      { label: '여성', agree: 29800, disagree: 22100, total: 51900 },
    ],
  },
}
